import ajax from './ajax';
export const reqRegister = (obj) => ajax('/register', obj, 'POST');
export const reqLogin = (obj) => ajax('/login',obj,'POST');
export const reqAutoLogin = () => ajax('/autoLogin');
export const reqRecommend = () => ajax("/recommend");
export const reqNote = (obj) => ajax('/note',obj,'POST');
export const reqNotes = () => ajax('/getNotes');
export const reqLike = (note_id) => ajax('/like', note_id, 'POST');
export const reqUnLike = (note_id) => ajax('/unlike',note_id,'POST');
export const reqAddTag = (tag) => ajax('/addTag', tag, 'POST');
export const reqRemoveTag = (tag) => ajax('/removeTag', tag , 'POST');
export const reqUser = (_id) => ajax("/user", _id, 'POST');
export const reqFollow = (follow_id) => ajax('/follow', follow_id, 'POST');
export const reqUnFollow = (unFollow_id) => ajax('/unFollow', unFollow_id, 'POST');
export const reqUsersObjs = (_id) => ajax('/getUsersObjs', _id, 'POST');
export const reqUsers2Objs = (_id) => ajax('/getUsers2Objs', _id, 'POST');
export const reqCards = (_id) => ajax('/getCards', _id, 'POST');
export const reqCard = (_id) => ajax('/getCard', _id, 'POST');
export const reqComment = (obj) => ajax('/comment', obj, 'POST');
export const reqComments = (note_id) => ajax("/comments", note_id, 'POST');